spring.application.name=et-classic-water-bill
# Database URL, username, and password
spring.datasource.url=jdbc:postgresql://localhost:5432/etclassicdb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


